### ISSUE TITLE
Could you provide tutorial about how you compiled it?

### ISSUE THREAD

**Issue by nyngwang** [HyungJu/code-blocks-mac#2]
I got this error:

<img src="https://user-images.githubusercontent.com/24765272/112846072-35824e80-90d8-11eb-8630-b36534a936de.jpeg" width="300">

Could you provide a step-by-step tutorial for this? So I can fix this myself.

**Comment by HyungJu** [comment]
Hi @nyngwang
I just followed [build instruction](https://github.com/svn2github/CodeBlocks/blob/master/BUILD) on CodeBlocks source code.
It produces executable file for macos, and then just packaged it to dmg format.
but i'm not sure codeblocks will work on big sur if you recompile them from the latest code because they dropped support for macos :(

**Comment by nyngwang** [comment]
CodeBlocks have blocked us, cool.
